<?xml version="1.0" encoding="utf-8"?><Database Name="LPG_DEV" Class="AccountDataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=LPG_DEV;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LPG_DEVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="stamnummer" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="paswoord" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="rol" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>