#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LPG_DEV")]
	public partial class AdminClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdministrator(Administrator instance);
    partial void UpdateAdministrator(Administrator instance);
    partial void DeleteAdministrator(Administrator instance);
    #endregion
		
		public AdminClassDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LPG_DEVConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdminClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdminClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdminClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdminClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administrator> Administrators
		{
			get
			{
				return this.GetTable<Administrator>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrators")]
	public partial class Administrator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _stamnummer;
		
		private string _adm_naam;
		
		private string _adm_voornaam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstamnummerChanging(int value);
    partial void OnstamnummerChanged();
    partial void Onadm_naamChanging(string value);
    partial void Onadm_naamChanged();
    partial void Onadm_voornaamChanging(string value);
    partial void Onadm_voornaamChanged();
    #endregion
		
		public Administrator()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stamnummer", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int stamnummer
		{
			get
			{
				return this._stamnummer;
			}
			set
			{
				if ((this._stamnummer != value))
				{
					this.OnstamnummerChanging(value);
					this.SendPropertyChanging();
					this._stamnummer = value;
					this.SendPropertyChanged("stamnummer");
					this.OnstamnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm_naam", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string adm_naam
		{
			get
			{
				return this._adm_naam;
			}
			set
			{
				if ((this._adm_naam != value))
				{
					this.Onadm_naamChanging(value);
					this.SendPropertyChanging();
					this._adm_naam = value;
					this.SendPropertyChanged("adm_naam");
					this.Onadm_naamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm_voornaam", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string adm_voornaam
		{
			get
			{
				return this._adm_voornaam;
			}
			set
			{
				if ((this._adm_voornaam != value))
				{
					this.Onadm_voornaamChanging(value);
					this.SendPropertyChanging();
					this._adm_voornaam = value;
					this.SendPropertyChanged("adm_voornaam");
					this.Onadm_voornaamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
