#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LPG_DEV")]
	public partial class TestchauffeurClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTestChauffeur(TestChauffeur instance);
    partial void UpdateTestChauffeur(TestChauffeur instance);
    partial void DeleteTestChauffeur(TestChauffeur instance);
    #endregion
		
		public TestchauffeurClassDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LPG_DEVConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TestchauffeurClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestchauffeurClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestchauffeurClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestchauffeurClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TestChauffeur> TestChauffeurs
		{
			get
			{
				return this.GetTable<TestChauffeur>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestChauffeurs")]
	public partial class TestChauffeur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _stamnummer;
		
		private string _chauf_naam;
		
		private string _chauf_voornaam;
		
		private string _chauf_ploeg;
		
		private string _chauf_niveau;
		
		private string _Wachtwoord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstamnummerChanging(string value);
    partial void OnstamnummerChanged();
    partial void Onchauf_naamChanging(string value);
    partial void Onchauf_naamChanged();
    partial void Onchauf_voornaamChanging(string value);
    partial void Onchauf_voornaamChanged();
    partial void Onchauf_ploegChanging(string value);
    partial void Onchauf_ploegChanged();
    partial void Onchauf_niveauChanging(string value);
    partial void Onchauf_niveauChanged();
    partial void OnWachtwoordChanging(string value);
    partial void OnWachtwoordChanged();
    #endregion
		
		public TestChauffeur()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stamnummer", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string stamnummer
		{
			get
			{
				return this._stamnummer;
			}
			set
			{
				if ((this._stamnummer != value))
				{
					this.OnstamnummerChanging(value);
					this.SendPropertyChanging();
					this._stamnummer = value;
					this.SendPropertyChanged("stamnummer");
					this.OnstamnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chauf_naam", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string chauf_naam
		{
			get
			{
				return this._chauf_naam;
			}
			set
			{
				if ((this._chauf_naam != value))
				{
					this.Onchauf_naamChanging(value);
					this.SendPropertyChanging();
					this._chauf_naam = value;
					this.SendPropertyChanged("chauf_naam");
					this.Onchauf_naamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chauf_voornaam", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string chauf_voornaam
		{
			get
			{
				return this._chauf_voornaam;
			}
			set
			{
				if ((this._chauf_voornaam != value))
				{
					this.Onchauf_voornaamChanging(value);
					this.SendPropertyChanging();
					this._chauf_voornaam = value;
					this.SendPropertyChanged("chauf_voornaam");
					this.Onchauf_voornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chauf_ploeg", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string chauf_ploeg
		{
			get
			{
				return this._chauf_ploeg;
			}
			set
			{
				if ((this._chauf_ploeg != value))
				{
					this.Onchauf_ploegChanging(value);
					this.SendPropertyChanging();
					this._chauf_ploeg = value;
					this.SendPropertyChanged("chauf_ploeg");
					this.Onchauf_ploegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chauf_niveau", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string chauf_niveau
		{
			get
			{
				return this._chauf_niveau;
			}
			set
			{
				if ((this._chauf_niveau != value))
				{
					this.Onchauf_niveauChanging(value);
					this.SendPropertyChanging();
					this._chauf_niveau = value;
					this.SendPropertyChanged("chauf_niveau");
					this.Onchauf_niveauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wachtwoord", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Wachtwoord
		{
			get
			{
				return this._Wachtwoord;
			}
			set
			{
				if ((this._Wachtwoord != value))
				{
					this.OnWachtwoordChanging(value);
					this.SendPropertyChanging();
					this._Wachtwoord = value;
					this.SendPropertyChanged("Wachtwoord");
					this.OnWachtwoordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
