#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LPG_DEV")]
	public partial class TestwagenClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTestwagen(Testwagen instance);
    partial void UpdateTestwagen(Testwagen instance);
    partial void DeleteTestwagen(Testwagen instance);
    #endregion
		
		public TestwagenClassDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LPG_DEVConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TestwagenClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestwagenClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestwagenClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestwagenClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Testwagen> Testwagens
		{
			get
			{
				return this.GetTable<Testwagen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Testwagen")]
	public partial class Testwagen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WagenNr;
		
		private int _tablet_id;
		
		private string _testwagen_type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWagenNrChanging(string value);
    partial void OnWagenNrChanged();
    partial void Ontablet_idChanging(int value);
    partial void Ontablet_idChanged();
    partial void Ontestwagen_typeChanging(string value);
    partial void Ontestwagen_typeChanged();
    #endregion
		
		public Testwagen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WagenNr", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WagenNr
		{
			get
			{
				return this._WagenNr;
			}
			set
			{
				if ((this._WagenNr != value))
				{
					this.OnWagenNrChanging(value);
					this.SendPropertyChanging();
					this._WagenNr = value;
					this.SendPropertyChanged("WagenNr");
					this.OnWagenNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tablet_id", DbType="Int NOT NULL")]
		public int tablet_id
		{
			get
			{
				return this._tablet_id;
			}
			set
			{
				if ((this._tablet_id != value))
				{
					this.Ontablet_idChanging(value);
					this.SendPropertyChanging();
					this._tablet_id = value;
					this.SendPropertyChanged("tablet_id");
					this.Ontablet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testwagen_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string testwagen_type
		{
			get
			{
				return this._testwagen_type;
			}
			set
			{
				if ((this._testwagen_type != value))
				{
					this.Ontestwagen_typeChanging(value);
					this.SendPropertyChanging();
					this._testwagen_type = value;
					this.SendPropertyChanged("testwagen_type");
					this.Ontestwagen_typeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
