<?xml version="1.0" encoding="utf-8"?><Database Name="LPG_DEV" Class="TestchauffeurClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=LPG_DEV;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LPG_DEVConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TestChauffeurs" Member="TestChauffeurs">
    <Type Name="TestChauffeur">
      <Column Name="stamnummer" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="chauf_naam" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="chauf_voornaam" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="chauf_ploeg" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="chauf_niveau" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Wachtwoord" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>