<?xml version="1.0" encoding="utf-8"?><Database Name="LPG_DEV" Class="AdminClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=LPG_DEV;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LPG_DEVConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Administrators" Member="Administrators">
    <Type Name="Administrator">
      <Column Name="stamnummer" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="adm_naam" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="adm_voornaam" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>