#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LPG_DEV")]
	public partial class CyclusClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCyclus(Cyclus instance);
    partial void UpdateCyclus(Cyclus instance);
    partial void DeleteCyclus(Cyclus instance);
    #endregion
		
		public CyclusClassDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LPG_DEVConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CyclusClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CyclusClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CyclusClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CyclusClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cyclus> Cyclus
		{
			get
			{
				return this.GetTable<Cyclus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cyclus")]
	public partial class Cyclus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cycl_code;
		
		private string _cycl_belading;
		
		private string _cycl_schakelmodus;
		
		private string _cycl_adaptive_damping;
		
		private string _cycl_hill_launch_assist;
		
		private int _cycl_cycli;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncycl_codeChanging(string value);
    partial void Oncycl_codeChanged();
    partial void Oncycl_beladingChanging(string value);
    partial void Oncycl_beladingChanged();
    partial void Oncycl_schakelmodusChanging(string value);
    partial void Oncycl_schakelmodusChanged();
    partial void Oncycl_adaptive_dampingChanging(string value);
    partial void Oncycl_adaptive_dampingChanged();
    partial void Oncycl_hill_launch_assistChanging(string value);
    partial void Oncycl_hill_launch_assistChanged();
    partial void Oncycl_cycliChanging(int value);
    partial void Oncycl_cycliChanged();
    #endregion
		
		public Cyclus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycl_code", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cycl_code
		{
			get
			{
				return this._cycl_code;
			}
			set
			{
				if ((this._cycl_code != value))
				{
					this.Oncycl_codeChanging(value);
					this.SendPropertyChanging();
					this._cycl_code = value;
					this.SendPropertyChanged("cycl_code");
					this.Oncycl_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycl_belading", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cycl_belading
		{
			get
			{
				return this._cycl_belading;
			}
			set
			{
				if ((this._cycl_belading != value))
				{
					this.Oncycl_beladingChanging(value);
					this.SendPropertyChanging();
					this._cycl_belading = value;
					this.SendPropertyChanged("cycl_belading");
					this.Oncycl_beladingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycl_schakelmodus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cycl_schakelmodus
		{
			get
			{
				return this._cycl_schakelmodus;
			}
			set
			{
				if ((this._cycl_schakelmodus != value))
				{
					this.Oncycl_schakelmodusChanging(value);
					this.SendPropertyChanging();
					this._cycl_schakelmodus = value;
					this.SendPropertyChanged("cycl_schakelmodus");
					this.Oncycl_schakelmodusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycl_adaptive_damping", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cycl_adaptive_damping
		{
			get
			{
				return this._cycl_adaptive_damping;
			}
			set
			{
				if ((this._cycl_adaptive_damping != value))
				{
					this.Oncycl_adaptive_dampingChanging(value);
					this.SendPropertyChanging();
					this._cycl_adaptive_damping = value;
					this.SendPropertyChanged("cycl_adaptive_damping");
					this.Oncycl_adaptive_dampingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycl_hill_launch_assist", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cycl_hill_launch_assist
		{
			get
			{
				return this._cycl_hill_launch_assist;
			}
			set
			{
				if ((this._cycl_hill_launch_assist != value))
				{
					this.Oncycl_hill_launch_assistChanging(value);
					this.SendPropertyChanging();
					this._cycl_hill_launch_assist = value;
					this.SendPropertyChanged("cycl_hill_launch_assist");
					this.Oncycl_hill_launch_assistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycl_cycli", DbType="Int NOT NULL")]
		public int cycl_cycli
		{
			get
			{
				return this._cycl_cycli;
			}
			set
			{
				if ((this._cycl_cycli != value))
				{
					this.Oncycl_cycliChanging(value);
					this.SendPropertyChanging();
					this._cycl_cycli = value;
					this.SendPropertyChanged("cycl_cycli");
					this.Oncycl_cycliChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
