#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LPG_DEV")]
	public partial class EventsOpvolgingClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEventsOpvolging(EventsOpvolging instance);
    partial void UpdateEventsOpvolging(EventsOpvolging instance);
    partial void DeleteEventsOpvolging(EventsOpvolging instance);
    #endregion
		
		public EventsOpvolgingClassDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LPG_DEVConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EventsOpvolgingClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventsOpvolgingClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventsOpvolgingClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventsOpvolgingClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EventsOpvolging> EventsOpvolgings
		{
			get
			{
				return this.GetTable<EventsOpvolging>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EventsOpvolging")]
	public partial class EventsOpvolging : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _volgorde;
		
		private string _baan;
		
		private string _naam;
		
		private int _codeEvent;
		
		private string _idCyclusblad;
		
		private int _versnelling;
		
		private int _snelheid;
		
		private int _frequentie;
		
		private string _cel1;
		
		private string _cel2;
		
		private string _cel3;
		
		private string _cel4;
		
		private string _cel5;
		
		private string _cel6;
		
		private string _cel7;
		
		private string _cel8;
		
		private string _cel9;
		
		private string _cel10;
		
		private string _cel11;
		
		private string _cel12;
		
		private string _cel13;
		
		private string _cel14;
		
		private string _cel15;
		
		private string _cel16;
		
		private string _cel17;
		
		private string _cel18;
		
		private string _cel19;
		
		private string _cel20;
		
		private string _cel21;
		
		private string _cel22;
		
		private string _cel23;
		
		private string _cel24;
		
		private string _cel25;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnvolgordeChanging(int value);
    partial void OnvolgordeChanged();
    partial void OnbaanChanging(string value);
    partial void OnbaanChanged();
    partial void OnnaamChanging(string value);
    partial void OnnaamChanged();
    partial void OncodeEventChanging(int value);
    partial void OncodeEventChanged();
    partial void OnidCyclusbladChanging(string value);
    partial void OnidCyclusbladChanged();
    partial void OnversnellingChanging(int value);
    partial void OnversnellingChanged();
    partial void OnsnelheidChanging(int value);
    partial void OnsnelheidChanged();
    partial void OnfrequentieChanging(int value);
    partial void OnfrequentieChanged();
    partial void Oncel1Changing(string value);
    partial void Oncel1Changed();
    partial void Oncel2Changing(string value);
    partial void Oncel2Changed();
    partial void Oncel3Changing(string value);
    partial void Oncel3Changed();
    partial void Oncel4Changing(string value);
    partial void Oncel4Changed();
    partial void Oncel5Changing(string value);
    partial void Oncel5Changed();
    partial void Oncel6Changing(string value);
    partial void Oncel6Changed();
    partial void Oncel7Changing(string value);
    partial void Oncel7Changed();
    partial void Oncel8Changing(string value);
    partial void Oncel8Changed();
    partial void Oncel9Changing(string value);
    partial void Oncel9Changed();
    partial void Oncel10Changing(string value);
    partial void Oncel10Changed();
    partial void Oncel11Changing(string value);
    partial void Oncel11Changed();
    partial void Oncel12Changing(string value);
    partial void Oncel12Changed();
    partial void Oncel13Changing(string value);
    partial void Oncel13Changed();
    partial void Oncel14Changing(string value);
    partial void Oncel14Changed();
    partial void Oncel15Changing(string value);
    partial void Oncel15Changed();
    partial void Oncel16Changing(string value);
    partial void Oncel16Changed();
    partial void Oncel17Changing(string value);
    partial void Oncel17Changed();
    partial void Oncel18Changing(string value);
    partial void Oncel18Changed();
    partial void Oncel19Changing(string value);
    partial void Oncel19Changed();
    partial void Oncel20Changing(string value);
    partial void Oncel20Changed();
    partial void Oncel21Changing(string value);
    partial void Oncel21Changed();
    partial void Oncel22Changing(string value);
    partial void Oncel22Changed();
    partial void Oncel23Changing(string value);
    partial void Oncel23Changed();
    partial void Oncel24Changing(string value);
    partial void Oncel24Changed();
    partial void Oncel25Changing(string value);
    partial void Oncel25Changed();
    #endregion
		
		public EventsOpvolging()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volgorde", DbType="Int NOT NULL")]
		public int volgorde
		{
			get
			{
				return this._volgorde;
			}
			set
			{
				if ((this._volgorde != value))
				{
					this.OnvolgordeChanging(value);
					this.SendPropertyChanging();
					this._volgorde = value;
					this.SendPropertyChanged("volgorde");
					this.OnvolgordeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baan", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string baan
		{
			get
			{
				return this._baan;
			}
			set
			{
				if ((this._baan != value))
				{
					this.OnbaanChanging(value);
					this.SendPropertyChanging();
					this._baan = value;
					this.SendPropertyChanged("baan");
					this.OnbaanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this.OnnaamChanging(value);
					this.SendPropertyChanging();
					this._naam = value;
					this.SendPropertyChanged("naam");
					this.OnnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeEvent", DbType="Int NOT NULL")]
		public int codeEvent
		{
			get
			{
				return this._codeEvent;
			}
			set
			{
				if ((this._codeEvent != value))
				{
					this.OncodeEventChanging(value);
					this.SendPropertyChanging();
					this._codeEvent = value;
					this.SendPropertyChanged("codeEvent");
					this.OncodeEventChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCyclusblad", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string idCyclusblad
		{
			get
			{
				return this._idCyclusblad;
			}
			set
			{
				if ((this._idCyclusblad != value))
				{
					this.OnidCyclusbladChanging(value);
					this.SendPropertyChanging();
					this._idCyclusblad = value;
					this.SendPropertyChanged("idCyclusblad");
					this.OnidCyclusbladChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_versnelling", DbType="Int NOT NULL")]
		public int versnelling
		{
			get
			{
				return this._versnelling;
			}
			set
			{
				if ((this._versnelling != value))
				{
					this.OnversnellingChanging(value);
					this.SendPropertyChanging();
					this._versnelling = value;
					this.SendPropertyChanged("versnelling");
					this.OnversnellingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snelheid", DbType="Int NOT NULL")]
		public int snelheid
		{
			get
			{
				return this._snelheid;
			}
			set
			{
				if ((this._snelheid != value))
				{
					this.OnsnelheidChanging(value);
					this.SendPropertyChanging();
					this._snelheid = value;
					this.SendPropertyChanged("snelheid");
					this.OnsnelheidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frequentie", DbType="Int NOT NULL")]
		public int frequentie
		{
			get
			{
				return this._frequentie;
			}
			set
			{
				if ((this._frequentie != value))
				{
					this.OnfrequentieChanging(value);
					this.SendPropertyChanging();
					this._frequentie = value;
					this.SendPropertyChanged("frequentie");
					this.OnfrequentieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel1", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel1
		{
			get
			{
				return this._cel1;
			}
			set
			{
				if ((this._cel1 != value))
				{
					this.Oncel1Changing(value);
					this.SendPropertyChanging();
					this._cel1 = value;
					this.SendPropertyChanged("cel1");
					this.Oncel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel2", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel2
		{
			get
			{
				return this._cel2;
			}
			set
			{
				if ((this._cel2 != value))
				{
					this.Oncel2Changing(value);
					this.SendPropertyChanging();
					this._cel2 = value;
					this.SendPropertyChanged("cel2");
					this.Oncel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel3", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel3
		{
			get
			{
				return this._cel3;
			}
			set
			{
				if ((this._cel3 != value))
				{
					this.Oncel3Changing(value);
					this.SendPropertyChanging();
					this._cel3 = value;
					this.SendPropertyChanged("cel3");
					this.Oncel3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel4", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel4
		{
			get
			{
				return this._cel4;
			}
			set
			{
				if ((this._cel4 != value))
				{
					this.Oncel4Changing(value);
					this.SendPropertyChanging();
					this._cel4 = value;
					this.SendPropertyChanged("cel4");
					this.Oncel4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel5", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel5
		{
			get
			{
				return this._cel5;
			}
			set
			{
				if ((this._cel5 != value))
				{
					this.Oncel5Changing(value);
					this.SendPropertyChanging();
					this._cel5 = value;
					this.SendPropertyChanged("cel5");
					this.Oncel5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel6", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel6
		{
			get
			{
				return this._cel6;
			}
			set
			{
				if ((this._cel6 != value))
				{
					this.Oncel6Changing(value);
					this.SendPropertyChanging();
					this._cel6 = value;
					this.SendPropertyChanged("cel6");
					this.Oncel6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel7", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel7
		{
			get
			{
				return this._cel7;
			}
			set
			{
				if ((this._cel7 != value))
				{
					this.Oncel7Changing(value);
					this.SendPropertyChanging();
					this._cel7 = value;
					this.SendPropertyChanged("cel7");
					this.Oncel7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel8", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel8
		{
			get
			{
				return this._cel8;
			}
			set
			{
				if ((this._cel8 != value))
				{
					this.Oncel8Changing(value);
					this.SendPropertyChanging();
					this._cel8 = value;
					this.SendPropertyChanged("cel8");
					this.Oncel8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel9", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel9
		{
			get
			{
				return this._cel9;
			}
			set
			{
				if ((this._cel9 != value))
				{
					this.Oncel9Changing(value);
					this.SendPropertyChanging();
					this._cel9 = value;
					this.SendPropertyChanged("cel9");
					this.Oncel9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel10", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel10
		{
			get
			{
				return this._cel10;
			}
			set
			{
				if ((this._cel10 != value))
				{
					this.Oncel10Changing(value);
					this.SendPropertyChanging();
					this._cel10 = value;
					this.SendPropertyChanged("cel10");
					this.Oncel10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel11", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel11
		{
			get
			{
				return this._cel11;
			}
			set
			{
				if ((this._cel11 != value))
				{
					this.Oncel11Changing(value);
					this.SendPropertyChanging();
					this._cel11 = value;
					this.SendPropertyChanged("cel11");
					this.Oncel11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel12", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel12
		{
			get
			{
				return this._cel12;
			}
			set
			{
				if ((this._cel12 != value))
				{
					this.Oncel12Changing(value);
					this.SendPropertyChanging();
					this._cel12 = value;
					this.SendPropertyChanged("cel12");
					this.Oncel12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel13", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel13
		{
			get
			{
				return this._cel13;
			}
			set
			{
				if ((this._cel13 != value))
				{
					this.Oncel13Changing(value);
					this.SendPropertyChanging();
					this._cel13 = value;
					this.SendPropertyChanged("cel13");
					this.Oncel13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel14", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel14
		{
			get
			{
				return this._cel14;
			}
			set
			{
				if ((this._cel14 != value))
				{
					this.Oncel14Changing(value);
					this.SendPropertyChanging();
					this._cel14 = value;
					this.SendPropertyChanged("cel14");
					this.Oncel14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel15", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel15
		{
			get
			{
				return this._cel15;
			}
			set
			{
				if ((this._cel15 != value))
				{
					this.Oncel15Changing(value);
					this.SendPropertyChanging();
					this._cel15 = value;
					this.SendPropertyChanged("cel15");
					this.Oncel15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel16", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel16
		{
			get
			{
				return this._cel16;
			}
			set
			{
				if ((this._cel16 != value))
				{
					this.Oncel16Changing(value);
					this.SendPropertyChanging();
					this._cel16 = value;
					this.SendPropertyChanged("cel16");
					this.Oncel16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel17", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel17
		{
			get
			{
				return this._cel17;
			}
			set
			{
				if ((this._cel17 != value))
				{
					this.Oncel17Changing(value);
					this.SendPropertyChanging();
					this._cel17 = value;
					this.SendPropertyChanged("cel17");
					this.Oncel17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel18", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel18
		{
			get
			{
				return this._cel18;
			}
			set
			{
				if ((this._cel18 != value))
				{
					this.Oncel18Changing(value);
					this.SendPropertyChanging();
					this._cel18 = value;
					this.SendPropertyChanged("cel18");
					this.Oncel18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel19", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel19
		{
			get
			{
				return this._cel19;
			}
			set
			{
				if ((this._cel19 != value))
				{
					this.Oncel19Changing(value);
					this.SendPropertyChanging();
					this._cel19 = value;
					this.SendPropertyChanged("cel19");
					this.Oncel19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel20", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel20
		{
			get
			{
				return this._cel20;
			}
			set
			{
				if ((this._cel20 != value))
				{
					this.Oncel20Changing(value);
					this.SendPropertyChanging();
					this._cel20 = value;
					this.SendPropertyChanged("cel20");
					this.Oncel20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel21", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel21
		{
			get
			{
				return this._cel21;
			}
			set
			{
				if ((this._cel21 != value))
				{
					this.Oncel21Changing(value);
					this.SendPropertyChanging();
					this._cel21 = value;
					this.SendPropertyChanged("cel21");
					this.Oncel21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel22", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel22
		{
			get
			{
				return this._cel22;
			}
			set
			{
				if ((this._cel22 != value))
				{
					this.Oncel22Changing(value);
					this.SendPropertyChanging();
					this._cel22 = value;
					this.SendPropertyChanged("cel22");
					this.Oncel22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel23", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel23
		{
			get
			{
				return this._cel23;
			}
			set
			{
				if ((this._cel23 != value))
				{
					this.Oncel23Changing(value);
					this.SendPropertyChanging();
					this._cel23 = value;
					this.SendPropertyChanged("cel23");
					this.Oncel23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel24", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel24
		{
			get
			{
				return this._cel24;
			}
			set
			{
				if ((this._cel24 != value))
				{
					this.Oncel24Changing(value);
					this.SendPropertyChanging();
					this._cel24 = value;
					this.SendPropertyChanged("cel24");
					this.Oncel24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel25", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cel25
		{
			get
			{
				return this._cel25;
			}
			set
			{
				if ((this._cel25 != value))
				{
					this.Oncel25Changing(value);
					this.SendPropertyChanging();
					this._cel25 = value;
					this.SendPropertyChanged("cel25");
					this.Oncel25Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
