#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LPG_DEV")]
	public partial class TestchauffeurPerCyclusDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTestchauffeurPerCyclus(TestchauffeurPerCyclus instance);
    partial void UpdateTestchauffeurPerCyclus(TestchauffeurPerCyclus instance);
    partial void DeleteTestchauffeurPerCyclus(TestchauffeurPerCyclus instance);
    #endregion
		
		public TestchauffeurPerCyclusDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LPG_DEVConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TestchauffeurPerCyclusDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestchauffeurPerCyclusDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestchauffeurPerCyclusDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestchauffeurPerCyclusDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TestchauffeurPerCyclus> TestchauffeurPerCyclus
		{
			get
			{
				return this.GetTable<TestchauffeurPerCyclus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestchauffeurPerCyclus")]
	public partial class TestchauffeurPerCyclus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _stamnummer;
		
		private int _cyclusblok_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstamnummerChanging(int value);
    partial void OnstamnummerChanged();
    partial void Oncyclusblok_idChanging(int value);
    partial void Oncyclusblok_idChanged();
    #endregion
		
		public TestchauffeurPerCyclus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stamnummer", DbType="Int NOT NULL")]
		public int stamnummer
		{
			get
			{
				return this._stamnummer;
			}
			set
			{
				if ((this._stamnummer != value))
				{
					this.OnstamnummerChanging(value);
					this.SendPropertyChanging();
					this._stamnummer = value;
					this.SendPropertyChanged("stamnummer");
					this.OnstamnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cyclusblok_id", DbType="Int NOT NULL")]
		public int cyclusblok_id
		{
			get
			{
				return this._cyclusblok_id;
			}
			set
			{
				if ((this._cyclusblok_id != value))
				{
					this.Oncyclusblok_idChanging(value);
					this.SendPropertyChanging();
					this._cyclusblok_id = value;
					this.SendPropertyChanged("cyclusblok_id");
					this.Oncyclusblok_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
